config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/proyects'
  get 'pages/contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def proyects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisProyectos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  </head>
  
  <body>  
    <div>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <h2 class= "mx-auto p-2">Proyecto Danny</h2>
        </div>
      </nav>    
    

 
    <div class= "container">
          <%= yield %>
    </div>
        <br>
        <br>

    

      <div>
        <div class="d-grid gap-2">
          <button class="btn btn-primary" ><%= link_to "Home", pages_home_path, class: "btn-link violet-link" %></button>
          <button class="btn btn-outline-primary" ><%= link_to "Proyects", pages_proyects_path, class: "btn-link violet-link" %></button>
          <button class="btn btn-outline-primary"><%= link_to "Contact", pages_contact_path, class: "btn-link violet-link" %></button>
        </div>
      </div>
    </div>
      </div>      
      </div>
    


    
    
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
 
  </body>


</html>

app/views/pages/contact.html.erb
<br>
<br>
<br>
<h1>Sígueme:</h1>

<div class="grid gap-80">
  <div class="p-2 g-col-12 d-flex justify-content-center gap-2">
    <a class="navbar-brand" target= "blank" href="https://twitter.com/daniela83861779">
      <i class="bi bi-twitter" style="font-size: 4rem"></i>
    </a>
    <a class="navbar-brand" target= "blank"href="https://www.instagram.com/cristttyyna/">
      <i class="bi bi-instagram" style="font-size: 4rem"></i>
    </a>
    <a class="navbar-brand" target= "blank" href="https://www.facebook.com/Nannyytta/">
      <i class="bi bi-facebook" style="font-size: 4rem"></i>
    </a>
    <a class="navbar-brand" target= "blank" href="https://github.com/Dannyytta">
      <i class="bi bi-github" style="font-size: 4rem"></i>
    </a>
  </div>
</div>

app/views/pages/home.html.erb
<br>
<br>
<br>
<h1 Class= "color-texto" >Experiencia</h1>
<br>
<p class="text-secondary"> Sin entender como llegué aquí, siento que fue parte destino, parte aburrimiento. Tenía tiempo y podía hacerme de más tiempo para cumplir esta meta. No es extraño en mí, verme haciendo varias cosas que no tienen relación entre ella, por lo menos no una directa. 
Soy itinerante y esa itinerancia me llevó a aquí, a este ahora. Son las tantas de la noche, mis niños y marido duermen y yo… disfrutando este momento de soledad y de estudio. Sintiéndome a ratos frustrada y otros muy motivada. Aprendiendo con este desafío que me propuse, cosas de mi que no tenía idea, descubriendo nuevos gustos y poniendo a prueba mi cerebro.
<br><br>Cosas q no esperaba para nada de esta experiencia:
El grupo humano que se formó.  Encantada de conocer sus personalidades, sus propuestas, sus historias. 
Soy una gran fan de las relaciones humanas, nunca había tenido una experiencia online de esta índole, en donde hay tanto feeling por medio de una “videollamada” con extraños. <br><br>
Bueno, cerrando y a lo q vinimos… a ver el book de la Danny. Solo comentar que más allá de lo difícil que ha sido para mí, entender como relacionar todo con el todo (respecto a los contenidos) he disfrutado cada error, cada hra de esta experiencia. Mis trabajos; creo q por ahí nomás. El tiempo apremia, por tanto, he entregado lo requerido por el programa-estudio y no, lo que me hubiera gustado entregar. 
 </p>
<p class="text-secondary"> PDT: Pensé q la pág se vería shorísima. Resutó ser feísima. jajajajaja</p>

app/views/pages/proyects.html.erb
<div class="mx-auto p-2" style="width: 200px;">
  <h1>Memorables</h1>
</div>
<br>
  <div class="row row-cols-1 row-cols-md-3 g-3">
  <div class="col">
    <div class="card">
    <div class="bg-dark p-2 text-dark bg-opacity-75">
      <img src="<%= asset_path "pag1.jpg" %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Meet&Coffe</h5>
        <p class="card-text">Unos de los trabajos que seguramente todos detestan. Solo el nombre me da escalofríos</p>
        <a href="#" class="btn btn-outline-primary"><h5 class= "texto-boton">RUN TO THE SITE</h5></a>
      </div>
    </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
    <div class="bg-dark p-2 text-dark bg-opacity-75">
      <img src="<%= asset_path "pagina2.jpg" %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Iguanas</h5>
        <p class="card-text">Es gracioso ir viendo los trabajos y recordar lo atrapada q estaba con algo ... medianamente simple. Obvio q relacionado con la informacion que hoy manejo. No es q sea seca, claramente!</p>
        <a href="#" class="btn btn-outline-primary"><h5 class= "texto-boton">RUN TO THE SITE</h5></a>
      </div>
    </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
    <div class="bg-dark p-2 text-dark bg-opacity-75">
      <img src="<%= asset_path "pagina3.jpg" %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Suricata</h5>
        <p class="card-text">Que dificil fue integrar esas "cards" y que quedaran como esperaba que quedaran. Hoy casi ni caxé como lo hice (creo que llegué y pegué bien el código nada más). Igual tenia una difícultad enorme... Recuerdo como sufrí con los íconos y su pocisionamiento.</p>
        <a href="#" class="btn btn-outline-primary"><h5 class= "texto-boton">RUN TO THE SITE</h5></a>
      </div>
    </div>
    </div>
  </div>
</div>
<br>